language: node_js
node_js:
- '8'

script:
- npm run lint
- echo "Running unit tests"
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
- echo "Running integration tests"
- npm run integration
